version: '3.3'

services:
  postgres:
    container_name: otus-postgres
    hostname: otus-postgres
    image: postgres:13
    ports:
       - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  pgadmin:
    container_name: otus-pgadmin
    hostname: otus-pgadmin
    build: ./docker/pgadmin
    ports:
      - "9090:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@localhost.local
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    depends_on:
      - postgres